"""inital commiit

Revision ID: 0558822762a8
Revises: 2b7380507a71
Create Date: 2022-12-24 12:27:26.366862

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0558822762a8"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dummy_model", sa.Column("year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dummy_model", "year")
    # ### end Alembic commands ###
