"""empty message

Revision ID: 35e1edf0a3fd
Revises: 104e922a81c4
Create Date: 2022-12-24 11:08:07.922222

"""

# revision identifiers, used by Alembic.
revision = "35e1edf0a3fd"
down_revision = "104e922a81c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
