"""empty message

Revision ID: 104e922a81c4
Revises: 70fdfa4178e1
Create Date: 2022-12-24 11:05:44.267011

"""

# revision identifiers, used by Alembic.
revision = "104e922a81c4"
down_revision = "70fdfa4178e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
